"""
Script to import CAEN codes from ONRC website into MongoDB
Source: https://www.onrc.ro/index.php/ro/conversie-caen-rev-2-caen-rev-3

CAEN = Clasificarea Activitatilor din Economia Nationala (Romanian NACE equivalent)

Usage:
    python scripts/import_caen_codes.py
"""

import asyncio
import sys
import os
from pathlib import Path
from urllib.parse import unquote

# Add parent directory to path for imports
sys.path.insert(0, str(Path(__file__).parent.parent))

from motor.motor_asyncio import AsyncIOMotorClient
from dotenv import load_dotenv

# Load environment variables
env_path = Path(__file__).parent.parent / '.env'
load_dotenv(dotenv_path=env_path)

# Complete CAEN Rev.2 codes extracted from ONRC website
# Format: (code, description)
CAEN_REV2_CODES = [
    ("0111", "Cultivarea cerealelor (exclusiv orez), plantelor leguminoase și a plantelor producătoare de semințe oleaginoase"),
    ("0112", "Cultivarea orezului"),
    ("0113", "Cultivarea legumelor și a pepenilor, a rădăcinoaselor și tuberculilor"),
    ("0114", "Cultivarea trestiei de zahăr"),
    ("0115", "Cultivarea tutunului"),
    ("0116", "Cultivarea plantelor pentru fibre textile"),
    ("0119", "Cultivarea altor plante din culturi nepermanente"),
    ("0121", "Cultivarea strugurilor"),
    ("0122", "Cultivarea fructelor tropicale și subtropicale"),
    ("0123", "Cultivarea fructelor citrice"),
    ("0124", "Cultivarea fructelor semințoase și sâmburoase"),
    ("0125", "Cultivarea fructelor arbuștilor fructiferi, căpșunilor, nuciferilor și a altor pomi fructiferi"),
    ("0126", "Cultivarea fructelor oleaginoase"),
    ("0127", "Cultivarea plantelor pentru prepararea băuturilor"),
    ("0128", "Cultivarea condimentelor, plantelor aromatice, medicinale și a plantelor de uz farmaceutic"),
    ("0129", "Cultivarea altor plante permanente"),
    ("0130", "Cultivarea plantelor pentru înmulțire"),
    ("0141", "Creșterea bovinelor de lapte"),
    ("0142", "Creșterea altor bovine"),
    ("0143", "Creșterea cailor și a altor cabaline"),
    ("0144", "Creșterea cămilelor și a camelidelor"),
    ("0145", "Creșterea ovinelor și caprinelor"),
    ("0146", "Creșterea porcinelor"),
    ("0147", "Creșterea păsărilor"),
    ("0149", "Creșterea altor animale"),
    ("0150", "Activități în ferme mixte (cultura vegetală combinată cu creșterea animalelor)"),
    ("0161", "Activități auxiliare pentru producția vegetală"),
    ("0162", "Activități auxiliare pentru creșterea animalelor"),
    ("0163", "Activități după recoltare"),
    ("0164", "Pregătirea semințelor"),
    ("0170", "Vânătoare, capturarea cu capcane a vânatului și activități de servicii anexe vânătorii"),
    ("0210", "Silvicultură și alte activități forestiere"),
    ("0220", "Exploatarea forestieră"),
    ("0230", "Colectarea produselor forestiere nelemnoase din flora spontană"),
    ("0240", "Activități de servicii anexe silviculturii"),
    ("0311", "Pescuitul maritim"),
    ("0312", "Pescuitul în ape dulci"),
    ("0321", "Acvacultura maritimă"),
    ("0322", "Acvacultura în ape dulci"),
    ("0510", "Extracția cărbunelui superior (PCS>=23865 kJ/kg)"),
    ("0520", "Extracția cărbunelui inferior (PCS<23865 kJ/kg)"),
    ("0610", "Extracția petrolului brut"),
    ("0620", "Extracția gazelor naturale"),
    ("0710", "Extracția minereurilor feroase"),
    ("0721", "Extracția minereurilor de uraniu și toriu"),
    ("0729", "Extracția altor minereuri metalifere neferoase"),
    ("0811", "Extracția pietrei ornamentale și a pietrei pentru construcții, extracția pietrei calcaroase, ghipsului, cretei și a ardeziei"),
    ("0812", "Extracția pietrișului și nisipului; extracția argilei și caolinului"),
    ("0891", "Extracția mineralelor pentru industria chimică și a îngrășămintelor naturale"),
    ("0892", "Extracția turbei"),
    ("0893", "Extracția sării"),
    ("0899", "Alte activități extractive n.c.a."),
    ("0910", "Activități de servicii anexe extracției petrolului brut și gazelor naturale"),
    ("0990", "Activități de servicii anexe pentru extracția mineralelor"),
    ("1011", "Prelucrarea și conservarea cărnii"),
    ("1012", "Prelucrarea și conservarea cărnii de pasăre"),
    ("1013", "Fabricarea produselor din carne (inclusiv din carne de pasăre)"),
    ("1020", "Prelucrarea și conservarea peștelui, crustaceelor și moluștelor"),
    ("1031", "Prelucrarea și conservarea cartofilor"),
    ("1032", "Fabricarea sucurilor de fructe și legume"),
    ("1039", "Prelucrarea și conservarea fructelor și legumelor n.c.a."),
    ("1041", "Fabricarea uleiurilor și grăsimilor"),
    ("1042", "Fabricarea margarinei și a altor produse comestibile similare"),
    ("1051", "Fabricarea produselor lactate și a brânzeturilor"),
    ("1052", "Fabricarea înghețatei"),
    ("1061", "Fabricarea produselor de morărit"),
    ("1062", "Fabricarea amidonului și a produselor din amidon"),
    ("1071", "Fabricarea pâinii; fabricarea prăjiturilor și a produselor proaspete de patiserie"),
    ("1072", "Fabricarea biscuiților și pișcoturilor; fabricarea prăjiturilor și a produselor conservate de patiserie"),
    ("1073", "Fabricarea macaroanelor, tăițeilor, cuș-cuș-ului și a altor produse făinoase similare"),
    ("1081", "Fabricarea zahărului"),
    ("1082", "Fabricarea produselor din cacao, a ciocolatei și a produselor zaharoase"),
    ("1083", "Prelucrarea ceaiului și cafelei"),
    ("1084", "Fabricarea condimentelor și ingredientelor"),
    ("1085", "Fabricarea de mâncăruri preparate"),
    ("1086", "Fabricarea preparatelor alimentare omogenizate și alimentelor dietetice"),
    ("1089", "Fabricarea altor produse alimentare n.c.a."),
    ("1091", "Fabricarea preparatelor pentru hrana animalelor de fermă"),
    ("1092", "Fabricarea preparatelor pentru hrana animalelor de companie"),
    ("1101", "Distilarea, rafinarea și mixarea băuturilor alcoolice"),
    ("1102", "Fabricarea vinurilor din struguri"),
    ("1103", "Fabricarea cidrului și a altor vinuri din fructe"),
    ("1104", "Fabricarea altor băuturi nedistilate, obținute prin fermentare"),
    ("1105", "Fabricarea berii"),
    ("1106", "Fabricarea malțului"),
    ("1107", "Producția de băuturi răcoritoare nealcoolice; producția de ape minerale și alte ape îmbuteliate"),
    ("1200", "Fabricarea produselor din tutun"),
    ("1310", "Pregătirea fibrelor și filarea fibrelor textile"),
    ("1320", "Producția de țesături"),
    ("1330", "Finisarea materialelor textile"),
    ("1391", "Fabricarea de metraje prin tricotare sau croșetare"),
    ("1392", "Fabricarea de articole confecționate din textile (cu excepția îmbrăcămintei și lenjeriei de corp)"),
    ("1393", "Fabricarea de covoare și mochete"),
    ("1394", "Fabricarea de odgoane, frânghii, sfori și plase"),
    ("1395", "Fabricarea de textile nețesute și articole din acestea, cu excepția confecțiilor de îmbrăcăminte"),
    ("1396", "Fabricarea de articole tehnice și industriale din textile"),
    ("1399", "Fabricarea altor articole textile n.c.a."),
    ("1411", "Fabricarea articolelor de îmbrăcăminte din piele"),
    ("1412", "Fabricarea de articole de îmbrăcăminte pentru lucru"),
    ("1413", "Fabricarea altor articole de îmbrăcăminte (exclusiv lenjeria de corp)"),
    ("1414", "Fabricarea de articole de lenjerie de corp"),
    ("1419", "Fabricarea altor articole de îmbrăcăminte și accesorii n.c.a."),
    ("1420", "Fabricarea articolelor din blană"),
    ("1431", "Fabricarea prin tricotare sau croșetare a ciorapilor și articolelor de galanterie"),
    ("1439", "Fabricarea prin tricotare sau croșetare a altor articole de îmbrăcăminte"),
    ("1511", "Tăbăcirea și finisarea pieilor; prepararea și vopsirea blănurilor"),
    ("1512", "Fabricarea articolelor de voiaj și marochinărie și a articolelor de harnașament"),
    ("1520", "Fabricarea încălțămintei"),
    ("1610", "Tăierea și rindeluirea lemnului"),
    ("1621", "Fabricarea de furnire și a panourilor de lemn"),
    ("1622", "Fabricarea parchetului asamblat în panouri"),
    ("1623", "Fabricarea altor elemente de dulgherie și tâmplărie, pentru construcții"),
    ("1624", "Fabricarea ambalajelor din lemn"),
    ("1629", "Fabricarea altor produse din lemn; fabricarea articolelor din plută, paie și din alte materiale vegetale împletite"),
    ("1711", "Fabricarea celulozei"),
    ("1712", "Fabricarea hârtiei și cartonului"),
    ("1721", "Fabricarea hârtiei și cartonului ondulat și a ambalajelor din hârtie și carton"),
    ("1722", "Fabricarea produselor de uz gospodăresc și sanitar, din hârtie sau carton"),
    ("1723", "Fabricarea articolelor de papetărie"),
    ("1724", "Fabricarea tapetului"),
    ("1729", "Fabricarea altor articole din hârtie și carton n.c.a."),
    ("1811", "Tipărirea ziarelor"),
    ("1812", "Alte activități de tipărire n.c.a."),
    ("1813", "Servicii pregătitoare pentru pretipărire"),
    ("1814", "Legătorie și servicii conexe"),
    ("1820", "Reproducerea înregistrărilor"),
    ("1910", "Fabricarea produselor de cocserie"),
    ("1920", "Fabricarea produselor obținute din prelucrarea țițeiului"),
    ("2011", "Fabricarea gazelor industriale"),
    ("2012", "Fabricarea coloranților și a pigmenților"),
    ("2013", "Fabricarea altor produse chimice anorganice, de bază"),
    ("2014", "Fabricarea altor produse chimice organice, de bază"),
    ("2015", "Fabricarea îngrășămintelor și produselor azotoase"),
    ("2016", "Fabricarea materialelor plastice în forme primare"),
    ("2017", "Fabricarea cauciucului sintetic în forme primare"),
    ("2020", "Fabricarea pesticidelor și a altor produse agrochimice"),
    ("2030", "Fabricarea vopselelor, lacurilor, cernelii tipografice și masticurilor"),
    ("2041", "Fabricarea săpunurilor, detergenților și a produselor de întreținere"),
    ("2042", "Fabricarea parfumurilor și a produselor cosmetice (de toaletă)"),
    ("2051", "Fabricarea explozivilor"),
    ("2052", "Fabricarea cleiurilor"),
    ("2053", "Fabricarea uleiurilor esențiale"),
    ("2059", "Fabricarea altor produse chimice n.c.a."),
    ("2060", "Fabricarea fibrelor sintetice și artificiale"),
    ("2110", "Fabricarea produselor farmaceutice de bază"),
    ("2120", "Fabricarea preparatelor farmaceutice"),
    ("2211", "Fabricarea anvelopelor și a camerelor de aer; reșaparea și refacerea anvelopelor"),
    ("2219", "Fabricarea altor produse din cauciuc"),
    ("2221", "Fabricarea plăcilor, foliilor, tuburilor și profilelor din material plastic"),
    ("2222", "Fabricarea articolelor de ambalaj din material plastic"),
    ("2223", "Fabricarea articolelor din material plastic pentru construcții"),
    ("2229", "Fabricarea altor produse din material plastic"),
    ("2311", "Fabricarea sticlei plate"),
    ("2312", "Prelucrarea și fasonarea sticlei plate"),
    ("2313", "Fabricarea articolelor din sticlă"),
    ("2314", "Fabricarea fibrelor din sticlă"),
    ("2319", "Fabricarea de sticlărie tehnică"),
    ("2320", "Fabricarea de produse refractare"),
    ("2331", "Fabricarea plăcilor și dalelor din ceramică"),
    ("2332", "Fabricarea cărămizilor, țiglelor și a altor produse pentru construcții, din argilă arsă"),
    ("2341", "Fabricarea articolelor ceramice pentru uz gospodăresc și ornamental"),
    ("2342", "Fabricarea de obiecte sanitare din ceramică"),
    ("2343", "Fabricarea izolatorilor și pieselor izolante din ceramică"),
    ("2344", "Fabricarea altor produse tehnice din ceramică"),
    ("2349", "Fabricarea altor produse ceramice n.c.a."),
    ("2351", "Fabricarea cimentului"),
    ("2352", "Fabricarea varului și ipsosului"),
    ("2361", "Fabricarea produselor din beton pentru construcții"),
    ("2362", "Fabricarea produselor din ipsos pentru construcții"),
    ("2363", "Fabricarea betonului"),
    ("2364", "Fabricarea mortarului"),
    ("2365", "Fabricarea produselor din azbociment"),
    ("2369", "Fabricarea altor articole din beton, ciment și ipsos"),
    ("2370", "Tăierea, fasonarea și finisarea pietrei"),
    ("2391", "Fabricarea de produse abrazive"),
    ("2399", "Fabricarea altor produse din minerale nemetalice, n.c.a."),
    ("2410", "Producția de metale feroase sub forme primare și de feroaliaje"),
    ("2420", "Producția de tuburi, țevi, profile tubulare și accesorii pentru acestea, din oțel"),
    ("2431", "Tragere la rece a barelor"),
    ("2432", "Laminare la rece a benzilor înguste"),
    ("2433", "Producția de profile obținute la rece"),
    ("2434", "Trefilarea firelor la rece"),
    ("2441", "Producția metalelor prețioase"),
    ("2442", "Metalurgia aluminiului"),
    ("2443", "Producția plumbului, zincului și cositorului"),
    ("2444", "Metalurgia cuprului"),
    ("2445", "Producția altor metale neferoase"),
    ("2446", "Prelucrarea combustibililor nucleari"),
    ("2451", "Turnarea fontei"),
    ("2452", "Turnarea oțelului"),
    ("2453", "Turnarea metalelor neferoase ușoare"),
    ("2454", "Turnarea altor metale neferoase"),
    ("2511", "Fabricarea de construcții metalice și părți componente ale structurilor metalice"),
    ("2512", "Fabricarea de uși și ferestre din metal"),
    ("2521", "Producția de radiatoare și cazane pentru încălzire centrală"),
    ("2529", "Producția de rezervoare, cisterne și containere metalice"),
    ("2530", "Producția generatoarelor de aburi (cu excepția cazanelor pentru încălzire centrală)"),
    ("2540", "Fabricarea armamentului și muniției"),
    ("2550", "Fabricarea produselor metalice obținute prin deformare plastică; metalurgia pulberilor"),
    ("2561", "Tratarea și acoperirea metalelor"),
    ("2562", "Operațiuni de mecanică generală"),
    ("2571", "Fabricarea produselor de tăiat"),
    ("2572", "Fabricarea articolelor de feronerie"),
    ("2573", "Fabricarea uneltelor"),
    ("2591", "Fabricarea de recipienți, containere și alte produse similare din oțel"),
    ("2592", "Fabricarea ambalajelor ușoare din metal"),
    ("2593", "Fabricarea articolelor din fire metalice; fabricarea de lanțuri și arcuri"),
    ("2594", "Fabricarea de șuruburi, buloane și alte articole filetate; fabricarea de nituri și șaibe"),
    ("2599", "Fabricarea altor articole din metal n.c.a."),
    ("2611", "Fabricarea subansamblurilor electronice (module)"),
    ("2612", "Fabricarea altor componente electronice"),
    ("2620", "Fabricarea calculatoarelor și a echipamentelor periferice"),
    ("2630", "Fabricarea echipamentelor de comunicații"),
    ("2640", "Fabricarea produselor electronice de larg consum"),
    ("2651", "Fabricarea de instrumente și dispozitive pentru măsură, verificare, control, navigație"),
    ("2652", "Producția de ceasuri"),
    ("2660", "Fabricarea de echipamente pentru radiologie, electrodiagnostic și electroterapie"),
    ("2670", "Fabricarea de instrumente optice și echipamente fotografice"),
    ("2680", "Fabricarea suporturilor magnetice și optice destinate înregistrărilor"),
    ("2711", "Fabricarea motoarelor, generatoarelor și transformatoarelor electrice"),
    ("2712", "Fabricarea aparatelor de distribuție și control a electricității"),
    ("2720", "Fabricarea de acumulatori și baterii"),
    ("2731", "Fabricarea de cabluri cu fibră optică"),
    ("2732", "Fabricarea altor fire și cabluri electrice și electronice"),
    ("2733", "Fabricarea dispozitivelor de conexiune pentru fire și cabluri electrice și electronice"),
    ("2740", "Fabricarea de echipamente electrice de iluminat"),
    ("2751", "Fabricarea de aparate electrocasnice"),
    ("2752", "Fabricarea de echipamente casnice neelectrice"),
    ("2790", "Fabricarea altor echipamente electrice"),
    ("2811", "Fabricarea de motoare și turbine (cu excepția celor pentru avioane, autovehicule și motociclete)"),
    ("2812", "Fabricarea de echipamente hidraulice și pneumatice"),
    ("2813", "Fabricarea de pompe și compresoare"),
    ("2814", "Fabricarea de articole de robinetărie"),
    ("2815", "Fabricarea lagărelor, angrenajelor, cutiilor de viteză și a elementelor mecanice de transmisie"),
    ("2821", "Fabricarea cuptoarelor, furnalelor și arzătoarelor"),
    ("2822", "Fabricarea echipamentelor de ridicat și manipulat"),
    ("2823", "Fabricarea mașinilor și echipamentelor de birou (exclusiv fabricarea calculatoarelor și a echipamentelor periferice)"),
    ("2824", "Fabricarea mașinilor-unelte portabile acționate electric"),
    ("2825", "Fabricarea echipamentelor de ventilație și frigorifice, exclusiv a echipamentelor de uz casnic"),
    ("2829", "Fabricarea altor mașini și utilaje de utilizare generală n.c.a."),
    ("2830", "Fabricarea mașinilor și utilajelor pentru agricultură și exploatări forestiere"),
    ("2841", "Fabricarea utilajelor și a mașinilor-unelte pentru prelucrarea metalului"),
    ("2849", "Fabricarea altor mașini-unelte"),
    ("2891", "Fabricarea utilajelor pentru metalurgie"),
    ("2892", "Fabricarea utilajelor pentru extracție și construcții"),
    ("2893", "Fabricarea utilajelor pentru prelucrarea produselor alimentare, băuturilor și tutunului"),
    ("2894", "Fabricarea utilajelor pentru industria textilă, a îmbrăcămintei și a pieilor"),
    ("2895", "Fabricarea utilajelor pentru industria hârtiei și cartonului"),
    ("2896", "Fabricarea utilajelor pentru prelucrarea maselor plastice și a cauciucului"),
    ("2899", "Fabricarea altor mașini și utilaje specifice n.c.a."),
    ("2910", "Fabricarea autovehiculelor de transport rutier"),
    ("2920", "Producția de caroserii pentru autovehicule; fabricarea de remorci și semiremorci"),
    ("2931", "Fabricarea de echipamente electrice și electronice pentru autovehicule și pentru motoare de autovehicule"),
    ("2932", "Fabricarea altor piese și accesorii pentru autovehicule și pentru motoare de autovehicule"),
    ("3011", "Construcția de nave și structuri plutitoare"),
    ("3012", "Construcția de ambarcațiuni sportive și de agrement"),
    ("3020", "Fabricarea materialului rulant"),
    ("3030", "Fabricarea de aeronave și nave spațiale"),
    ("3040", "Fabricarea vehiculelor militare de luptă"),
    ("3091", "Fabricarea de motociclete"),
    ("3092", "Fabricarea de biciclete și de vehicule pentru invalizi"),
    ("3099", "Fabricarea altor mijloace de transport n.c.a."),
    ("3101", "Fabricarea de mobilă pentru birouri și magazine"),
    ("3102", "Fabricarea de mobilă pentru bucătării"),
    ("3103", "Fabricarea de saltele și somiere"),
    ("3109", "Fabricarea de mobilier n.c.a."),
    ("3211", "Baterea monedelor"),
    ("3212", "Fabricarea bijuteriilor și articolelor similare din metale și pietre prețioase"),
    ("3213", "Fabricarea imitațiilor de bijuterii și articole similare"),
    ("3220", "Fabricarea instrumentelor muzicale"),
    ("3230", "Fabricarea articolelor pentru sport"),
    ("3240", "Fabricarea jocurilor și jucăriilor"),
    ("3250", "Fabricarea de dispozitive, aparate și instrumente medicale și stomatologice"),
    ("3291", "Fabricarea măturilor și periilor"),
    ("3299", "Fabricarea altor produse manufacturiere n.c.a."),
    ("3311", "Repararea articolelor fabricate din metal"),
    ("3312", "Repararea mașinilor"),
    ("3313", "Repararea echipamentelor electronice și optice"),
    ("3314", "Repararea echipamentelor electrice"),
    ("3315", "Repararea și întreținerea navelor și bărcilor"),
    ("3316", "Repararea și întreținerea aeronavelor și navelor spațiale"),
    ("3317", "Repararea și întreținerea altor echipamente de transport n.c.a."),
    ("3319", "Repararea altor echipamente"),
    ("3320", "Instalarea mașinilor și echipamentelor industriale"),
    ("3511", "Producția de energie electrică"),
    ("3512", "Transportul energiei electrice"),
    ("3513", "Distribuția energiei electrice"),
    ("3514", "Comercializarea energiei electrice"),
    ("3521", "Producția gazelor"),
    ("3522", "Distribuția combustibililor gazoși, prin conducte"),
    ("3523", "Comercializarea combustibililor gazoși, prin conducte"),
    ("3530", "Furnizarea de abur și aer condiționat"),
    ("3600", "Captarea, tratarea și distribuția apei"),
    ("3700", "Colectarea și epurarea apelor uzate"),
    ("3811", "Colectarea deșeurilor nepericuloase"),
    ("3812", "Colectarea deșeurilor periculoase"),
    ("3821", "Tratarea și eliminarea deșeurilor nepericuloase"),
    ("3822", "Tratarea și eliminarea deșeurilor periculoase"),
    ("3831", "Demontarea (dezasamblarea) mașinilor și echipamentelor scoase din uz pentru recuperarea materialelor"),
    ("3832", "Recuperarea materialelor reciclabile sortate"),
    ("3900", "Activități și servicii de decontaminare"),
    ("4110", "Dezvoltare (promovare) imobiliară"),
    ("4120", "Lucrări de construcție a clădirilor rezidențiale și nerezidențiale"),
    ("4211", "Lucrări de construcție a drumurilor și autostrăzilor"),
    ("4212", "Lucrări de construcție a căilor ferate de suprafață și subterane"),
    ("4213", "Construcția de poduri și tuneluri"),
    ("4221", "Lucrări de construcții a proiectelor utilitare pentru fluide"),
    ("4222", "Lucrări de construcții a proiectelor utilitare pentru electricitate și telecomunicații"),
    ("4291", "Construcții hidrotehnice"),
    ("4299", "Lucrări de construcție a altor proiecte inginerești n.c.a."),
    ("4311", "Lucrări de demolare a construcțiilor"),
    ("4312", "Lucrări de pregătire a terenului"),
    ("4313", "Lucrări de foraj și sondaj pentru construcții"),
    ("4321", "Lucrări de instalații electrice"),
    ("4322", "Lucrări de instalații sanitare, de încălzire și de aer condiționat"),
    ("4329", "Alte lucrări de instalații pentru construcții"),
    ("4331", "Lucrări de ipsoserie"),
    ("4332", "Lucrări de tâmplărie și dulgherie"),
    ("4333", "Lucrări de pardosire și placare a pereților"),
    ("4334", "Lucrări de vopsitorie, zugrăveli și montări de geamuri"),
    ("4339", "Alte lucrări de finisare"),
    ("4391", "Lucrări de învelitori, șarpante și terase la construcții"),
    ("4399", "Alte lucrări speciale de construcții n.c.a."),
    ("4511", "Comerț cu autoturisme și autovehicule ușoare (sub 3,5 tone)"),
    ("4519", "Comerț cu alte autovehicule"),
    ("4520", "Întreținerea și repararea autovehiculelor"),
    ("4531", "Comerț cu ridicata de piese și accesorii pentru autovehicule"),
    ("4532", "Comerț cu amănuntul de piese și accesorii pentru autovehicule"),
    ("4540", "Comerț cu motociclete, piese și accesorii aferente; întreținerea și repararea motocicletelor"),
    ("4611", "Intermedieri în comerțul cu materii prime agricole, animale vii, materii prime textile și cu semifabricate"),
    ("4612", "Intermedieri în comerțul cu combustibili, minereuri, metale și produse chimice pentru industrie"),
    ("4613", "Intermedieri în comerțul cu material lemnos și materiale de construcții"),
    ("4614", "Intermedieri în comerțul cu mașini, echipamente industriale, nave și avioane"),
    ("4615", "Intermedieri în comerțul cu mobilă, articole de menaj și de fierărie"),
    ("4616", "Intermedieri în comerțul cu textile, confecții din blană, încălțăminte și articole din piele"),
    ("4617", "Intermedieri în comerțul cu produse alimentare, băuturi și tutun"),
    ("4618", "Intermedieri în comerțul specializat în vânzarea produselor cu caracter specific, n.c.a."),
    ("4619", "Intermedieri în comerțul cu produse diverse"),
    ("4621", "Comerț cu ridicata al cerealelor, semințelor, furajelor și tutunului neprelucrat"),
    ("4622", "Comerț cu ridicata al florilor și al plantelor"),
    ("4623", "Comerț cu ridicata al animalelor vii"),
    ("4624", "Comerț cu ridicata al blănurilor, pieilor brute și al pieilor prelucrate"),
    ("4631", "Comerț cu ridicata al fructelor și legumelor"),
    ("4632", "Comerț cu ridicata al cărnii și produselor din carne"),
    ("4633", "Comerț cu ridicata al produselor lactate, ouălor, uleiurilor și grăsimilor comestibile"),
    ("4634", "Comerț cu ridicata al băuturilor"),
    ("4635", "Comerț cu ridicata al produselor din tutun"),
    ("4636", "Comerț cu ridicata al zahărului, ciocolatei și produselor zaharoase"),
    ("4637", "Comerț cu ridicata cu cafea, ceai, cacao și condimente"),
    ("4638", "Comerț cu ridicata specializat al altor alimente, inclusiv pește, crustacee și moluște"),
    ("4639", "Comerț cu ridicata nespecializat de produse alimentare, băuturi și tutun"),
    ("4641", "Comerț cu ridicata al produselor textile"),
    ("4642", "Comerț cu ridicata al îmbrăcămintei și încălțămintei"),
    ("4643", "Comerț cu ridicata al aparatelor electrice de uz gospodăresc, al aparatelor de radio și televizoarelor"),
    ("4644", "Comerț cu ridicata al produselor din ceramică, sticlărie și produse de întreținere"),
    ("4645", "Comerț cu ridicata al produselor cosmetice și de parfumerie"),
    ("4646", "Comerț cu ridicata al produselor farmaceutice"),
    ("4647", "Comerț cu ridicata al mobilei, covoarelor și a articolelor de iluminat"),
    ("4648", "Comerț cu ridicata al ceasurilor și bijuteriilor"),
    ("4649", "Comerț cu ridicata al altor bunuri de uz gospodăresc"),
    ("4651", "Comerț cu ridicata al calculatoarelor, echipamentelor periferice și software-ului"),
    ("4652", "Comerț cu ridicata de componente și echipamente electronice și de telecomunicații"),
    ("4661", "Comerț cu ridicata al mașinilor agricole, echipamentelor și furniturilor"),
    ("4662", "Comerț cu ridicata al mașinilor-unelte"),
    ("4663", "Comerț cu ridicata al mașinilor pentru industria minieră și construcții"),
    ("4664", "Comerț cu ridicata al mașinilor pentru industria textilă și al mașinilor de cusut și de tricotat"),
    ("4665", "Comerț cu ridicata al mobilei de birou"),
    ("4666", "Comerț cu ridicata al altor mașini și echipamente de birou"),
    ("4669", "Comerț cu ridicata al altor mașini și echipamente"),
    ("4671", "Comerț cu ridicata al combustibililor solizi, lichizi și gazoși și al produselor derivate"),
    ("4672", "Comerț cu ridicata al metalelor și minereurilor metalice"),
    ("4673", "Comerț cu ridicata al materialului lemnos și al materialelor de construcție și echipamentelor sanitare"),
    ("4674", "Comerț cu ridicata al echipamentelor și furniturilor de fierărie pentru instalații sanitare și de încălzire"),
    ("4675", "Comerț cu ridicata al produselor chimice"),
    ("4676", "Comerț cu ridicata al altor produse intermediare"),
    ("4677", "Comerț cu ridicata al deșeurilor și resturilor"),
    ("4690", "Comerț cu ridicata nespecializat"),
    ("4711", "Comerț cu amănuntul în magazine nespecializate, cu vânzare predominantă de produse alimentare, băuturi și tutun"),
    ("4719", "Comerț cu amănuntul în magazine nespecializate, cu vânzare predominantă de produse nealimentare"),
    ("4721", "Comerț cu amănuntul al fructelor și legumelor proaspete, în magazine specializate"),
    ("4722", "Comerț cu amănuntul al cărnii și al produselor din carne, în magazine specializate"),
    ("4723", "Comerț cu amănuntul al peștelui, crustaceelor și moluștelor, în magazine specializate"),
    ("4724", "Comerț cu amănuntul al pâinii, produselor de patiserie și produselor zaharoase, în magazine specializate"),
    ("4725", "Comerț cu amănuntul al băuturilor, în magazine specializate"),
    ("4726", "Comerț cu amănuntul al produselor din tutun, în magazine specializate"),
    ("4729", "Comerț cu amănuntul al altor produse alimentare, în magazine specializate"),
    ("4730", "Comerț cu amănuntul al carburanților pentru autovehicule, în magazine specializate"),
    ("4741", "Comerț cu amănuntul al calculatoarelor, unităților periferice și software-ului în magazine specializate"),
    ("4742", "Comerț cu amănuntul al echipamentului pentru telecomunicații în magazine specializate"),
    ("4743", "Comerț cu amănuntul al echipamentelor audio/video în magazine specializate"),
    ("4751", "Comerț cu amănuntul al textilelor, în magazine specializate"),
    ("4752", "Comerț cu amănuntul al articolelor de fierărie, al articolelor din sticlă și al celor pentru vopsit, în magazine specializate"),
    ("4753", "Comerț cu amănuntul al covoarelor, carpetelor, tapetelor și al altor acoperitoare de podea, în magazine specializate"),
    ("4754", "Comerț cu amănuntul al articolelor și aparatelor electrocasnice, în magazine specializate"),
    ("4759", "Comerț cu amănuntul al mobilei, al articolelor de iluminat și al articolelor de uz casnic n.c.a., în magazine specializate"),
    ("4761", "Comerț cu amănuntul al cărților, în magazine specializate"),
    ("4762", "Comerț cu amănuntul al ziarelor și articolelor de papetărie, în magazine specializate"),
    ("4763", "Comerț cu amănuntul al înregistrărilor muzicale și video, în magazine specializate"),
    ("4764", "Comerț cu amănuntul al echipamentelor sportive, în magazine specializate"),
    ("4765", "Comerț cu amănuntul al jocurilor și jucăriilor, în magazine specializate"),
    ("4771", "Comerț cu amănuntul al îmbrăcămintei, în magazine specializate"),
    ("4772", "Comerț cu amănuntul al încălțămintei și articolelor din piele, în magazine specializate"),
    ("4773", "Comerț cu amănuntul al produselor farmaceutice, în magazine specializate"),
    ("4774", "Comerț cu amănuntul al articolelor medicale și ortopedice, în magazine specializate"),
    ("4775", "Comerț cu amănuntul al produselor cosmetice și de parfumerie, în magazine specializate"),
    ("4776", "Comerț cu amănuntul al florilor, plantelor și semințelor; comerț cu amănuntul al animalelor de companie și al hranei pentru acestea, în magazine specializate"),
    ("4777", "Comerț cu amănuntul al ceasurilor și bijuteriilor, în magazine specializate"),
    ("4778", "Comerț cu amănuntul al altor bunuri noi, în magazine specializate"),
    ("4779", "Comerț cu amănuntul al bunurilor de ocazie vândute prin magazine"),
    ("4781", "Comerț cu amănuntul al produselor alimentare, băuturilor și produselor din tutun efectuat prin standuri, chioșcuri și piețe"),
    ("4782", "Comerț cu amănuntul al textilelor, îmbrăcămintei și încălțămintei efectuat prin standuri, chioșcuri și piețe"),
    ("4789", "Comerț cu amănuntul prin standuri, chioșcuri și piețe al altor produse"),
    ("4791", "Comerț cu amănuntul prin intermediul caselor de comenzi sau prin Internet"),
    ("4799", "Comerț cu amănuntul efectuat în afara magazinelor, standurilor, chioșcurilor și piețelor"),
    ("4910", "Transporturi interurbane de călători pe calea ferată"),
    ("4920", "Transporturi de marfă pe calea ferată"),
    ("4931", "Transporturi urbane, suburbane și metropolitane de călători"),
    ("4932", "Transporturi cu taxiuri"),
    ("4939", "Alte transporturi terestre de călători n.c.a."),
    ("4941", "Transporturi rutiere de mărfuri"),
    ("4942", "Servicii de mutare"),
    ("4950", "Transporturi prin conducte"),
    ("5010", "Transporturi maritime și costiere de pasageri"),
    ("5020", "Transporturi maritime și costiere de marfă"),
    ("5030", "Transportul de pasageri pe căi navigabile interioare"),
    ("5040", "Transportul de marfă pe căi navigabile interioare"),
    ("5110", "Transporturi aeriene de pasageri"),
    ("5121", "Transporturi aeriene de marfă"),
    ("5122", "Transporturi spațiale"),
    ("5210", "Depozitări"),
    ("5221", "Activități de servicii anexe pentru transporturi terestre"),
    ("5222", "Activități de servicii anexe transporturilor pe apă"),
    ("5223", "Activități de servicii anexe transporturilor aeriene"),
    ("5224", "Manipulări"),
    ("5229", "Alte activități anexe transporturilor"),
    ("5310", "Activități poștale desfășurate sub obligativitatea serviciului universal"),
    ("5320", "Alte activități poștale și de curier"),
    ("5510", "Hoteluri și alte facilități de cazare similare"),
    ("5520", "Facilități de cazare pentru vacanțe și perioade de scurtă durată"),
    ("5530", "Parcuri pentru rulote, campinguri și tabere"),
    ("5590", "Alte servicii de cazare"),
    ("5610", "Restaurante"),
    ("5621", "Activități de alimentație (catering) pentru evenimente"),
    ("5629", "Alte servicii de alimentație n.c.a."),
    ("5630", "Baruri și alte activități de servire a băuturilor"),
    ("5811", "Activități de editare a cărților"),
    ("5812", "Activități de editare a cataloagelor și listelor (ghidurilor)"),
    ("5813", "Activități de editare a ziarelor"),
    ("5814", "Activități de editare a revistelor și periodicelor"),
    ("5819", "Alte activități de editare"),
    ("5821", "Activități de editare a jocurilor de calculator"),
    ("5829", "Activități de editare a altor produse software"),
    ("5911", "Activități de producție cinematografică, video și de programe de televiziune"),
    ("5912", "Activități de post-producție cinematografică, video și de programe de televiziune"),
    ("5913", "Activități de distribuție a filmelor cinematografice, video și a programelor de televiziune"),
    ("5914", "Proiecția de filme cinematografice"),
    ("5920", "Activități de realizare a înregistrărilor audio și activități de editare muzicală"),
    ("6010", "Activități de difuzare a programelor de radio"),
    ("6020", "Activități de difuzare a programelor de televiziune"),
    ("6110", "Activități de telecomunicații prin rețele cu cablu"),
    ("6120", "Activități de telecomunicații prin rețele fără cablu (exclusiv prin satelit)"),
    ("6130", "Activități de telecomunicații prin satelit"),
    ("6190", "Alte activități de telecomunicații"),
    ("6201", "Activități de realizare a soft-ului la comandă (software orientat client)"),
    ("6202", "Activități de consultanță în tehnologia informației"),
    ("6203", "Activități de management (gestiune și exploatare) a mijloacelor de calcul"),
    ("6209", "Alte activități de servicii privind tehnologia informației"),
    ("6311", "Prelucrarea datelor, administrarea paginilor web și activități conexe"),
    ("6312", "Activități ale portalurilor web"),
    ("6391", "Activități ale agențiilor de știri"),
    ("6399", "Alte activități de servicii informaționale n.c.a."),
    ("6411", "Activități ale băncii centrale (naționale)"),
    ("6419", "Alte activități de intermedieri monetare"),
    ("6420", "Activități ale holdingurilor"),
    ("6430", "Fonduri mutuale și alte entități financiare similare"),
    ("6491", "Leasing financiar"),
    ("6492", "Alte activități de creditare"),
    ("6499", "Alte intermedieri financiare n.c.a."),
    ("6511", "Activități de asigurări de viață"),
    ("6512", "Alte activități de asigurări (exceptând asigurările de viață)"),
    ("6520", "Activități de reasigurare"),
    ("6530", "Activități ale fondurilor de pensii (cu excepția celor din sistemul public de asigurări sociale)"),
    ("6611", "Administrarea piețelor financiare"),
    ("6612", "Activități de intermediere a tranzacțiilor financiare"),
    ("6619", "Activități auxiliare intermedierilor financiare, exclusiv activități de asigurări și fonduri de pensii"),
    ("6621", "Activități de evaluare a riscului de asigurare și a pagubelor"),
    ("6622", "Activități ale agenților și broker-ilor de asigurări"),
    ("6629", "Alte activități auxiliare de asigurări și fonduri de pensii"),
    ("6630", "Activități de administrare a fondurilor"),
    ("6810", "Cumpărarea și vânzarea de bunuri imobiliare proprii"),
    ("6820", "Închirierea și subînchirierea bunurilor imobiliare proprii sau închiriate"),
    ("6831", "Agenții imobiliare"),
    ("6832", "Administrarea imobilelor pe bază de comision sau contract"),
    ("6910", "Activități juridice"),
    ("6920", "Activități de contabilitate și audit financiar; consultanță în domeniul fiscal"),
    ("7010", "Activități ale direcțiilor (centralelor), birourilor administrative centralizate"),
    ("7021", "Activități de consultanță în domeniul relațiilor publice și al comunicării"),
    ("7022", "Activități de consultanță pentru afaceri și management"),
    ("7111", "Activități de arhitectură"),
    ("7112", "Activități de inginerie și consultanță tehnică legate de acestea"),
    ("7120", "Activități de testări și analize tehnice"),
    ("7211", "Cercetare-dezvoltare în biotehnologie"),
    ("7219", "Cercetare-dezvoltare în alte științe naturale și inginerie"),
    ("7220", "Cercetare-dezvoltare în științe sociale și umaniste"),
    ("7311", "Activități ale agențiilor de publicitate"),
    ("7312", "Servicii de reprezentare media"),
    ("7320", "Activități de studiere a pieței și de sondare a opiniei publice"),
    ("7410", "Activități de design specializat"),
    ("7420", "Activități fotografice"),
    ("7430", "Activități de traducere scrisă și orală (interpreți)"),
    ("7490", "Alte activități profesionale, științifice și tehnice n.c.a."),
    ("7500", "Activități veterinare"),
    ("7711", "Activități de închiriere și leasing cu autoturisme și autovehicule rutiere ușoare"),
    ("7712", "Activități de închiriere și leasing cu autovehicule rutiere grele"),
    ("7721", "Activități de închiriere și leasing cu bunuri recreaționale și echipament sportiv"),
    ("7722", "Închirierea de casete video și discuri (CD-uri, DVD-uri)"),
    ("7729", "Activități de închiriere și leasing cu alte bunuri personale și gospodărești n.c.a."),
    ("7731", "Activități de închiriere și leasing cu mașini și echipamente agricole"),
    ("7732", "Activități de închiriere și leasing cu mașini și echipamente pentru construcții"),
    ("7733", "Activități de închiriere și leasing cu mașini și echipamente de birou (inclusiv calculatoare)"),
    ("7734", "Activități de închiriere și leasing cu mașini și echipamente de transport pe apă"),
    ("7735", "Activități de închiriere și leasing cu mașini și echipamente de transport aerian"),
    ("7739", "Activități de închiriere și leasing cu alte mașini, echipamente și bunuri tangibile n.c.a."),
    ("7740", "Leasing cu bunuri intangibile (exclusiv financiare)"),
    ("7810", "Activități ale agențiilor de plasare a forței de muncă"),
    ("7820", "Activități de contractare, pe baze temporare, a personalului"),
    ("7830", "Servicii de furnizare și management a forței de muncă"),
    ("7911", "Activități ale agențiilor turistice"),
    ("7912", "Activități ale tur-operatorilor"),
    ("7990", "Alte servicii de rezervare și asistență turistică"),
    ("8010", "Activități de protecție și gardă"),
    ("8020", "Activități de servicii privind sistemele de securizare"),
    ("8030", "Activități de investigații"),
    ("8110", "Activități de servicii suport combinate"),
    ("8121", "Activități generale de curățenie a clădirilor"),
    ("8122", "Activități specializate de curățenie"),
    ("8129", "Alte activități de curățenie"),
    ("8130", "Activități de întreținere peisagistică"),
    ("8211", "Activități combinate de secretariat"),
    ("8219", "Activități de fotocopiere, de pregătire a documentelor și alte activități specializate de secretariat"),
    ("8220", "Activități ale centrelor de intermediere telefonică (call center)"),
    ("8230", "Activități de organizare a expozițiilor, târgurilor și congreselor"),
    ("8291", "Activități ale agențiilor de colectare și a birourilor (oficiilor) de raportare a creditului"),
    ("8292", "Activități de ambalare"),
    ("8299", "Alte activități de servicii suport pentru întreprinderi n.c.a."),
    ("8411", "Servicii de administrație publică generală"),
    ("8412", "Reglementarea activităților organismelor care prestează servicii în domeniul îngrijirii sănătății, învățământului, culturii și al altor activități sociale, exclusiv protecția socială"),
    ("8413", "Reglementarea și eficientizarea activităților economice"),
    ("8421", "Activități de servicii externe"),
    ("8422", "Activități de apărare națională"),
    ("8423", "Activități de justiție"),
    ("8424", "Activități de ordine publică și de protecție civilă"),
    ("8425", "Activități de luptă împotriva incendiilor și de prevenire a acestora"),
    ("8430", "Activități de protecție socială obligatorie"),
    ("8510", "Învățământ preșcolar"),
    ("8520", "Învățământ primar"),
    ("8531", "Învățământ secundar general"),
    ("8532", "Învățământ secundar, tehnic sau profesional"),
    ("8541", "Învățământ superior non-universitar"),
    ("8542", "Învățământ superior universitar"),
    ("8551", "Învățământ în domeniul sportiv și recreațional"),
    ("8552", "Învățământ în domeniul cultural (limbi străine, muzică, teatru, dans, arte plastice, etc.)"),
    ("8553", "Școli de conducere (pilotaj)"),
    ("8559", "Alte forme de învățământ n.c.a."),
    ("8560", "Activități de servicii suport pentru învățământ"),
    ("8610", "Activități de asistență spitalicească"),
    ("8621", "Activități de asistență medicală generală"),
    ("8622", "Activități de asistență medicală specializată"),
    ("8623", "Activități de asistență stomatologică"),
    ("8690", "Alte activități referitoare la sănătatea umană"),
    ("8710", "Activități ale centrelor de îngrijire medicală"),
    ("8720", "Activități ale centrelor de recuperare psihică și de dezintoxicare, exclusiv spitale"),
    ("8730", "Activități ale căminelor de bătrâni și ale căminelor pentru persoane aflate în incapacitate de a se îngriji singure"),
    ("8790", "Alte activități de asistență socială, cu cazare n.c.a."),
    ("8810", "Activități de asistență socială, fără cazare, pentru bătrâni și pentru persoane aflate în incapacitate de a se îngriji singure"),
    ("8891", "Activități de îngrijire zilnică pentru copii"),
    ("8899", "Alte activități de asistență socială, fără cazare, n.c.a."),
    ("9001", "Activități de interpretare artistică (spectacole)"),
    ("9002", "Activități suport pentru interpretare artistică (spectacole)"),
    ("9003", "Activități de creație artistică"),
    ("9004", "Activități de gestionare a sălilor de spectacole"),
    ("9101", "Activități ale bibliotecilor și arhivelor"),
    ("9102", "Activități ale muzeelor"),
    ("9103", "Gestionarea monumentelor, clădirilor istorice și a altor obiective de interes turistic"),
    ("9104", "Activități ale grădinilor zoologice, botanice și ale rezervațiilor naturale"),
    ("9200", "Activități de jocuri de noroc și pariuri"),
    ("9311", "Activități ale bazelor sportive"),
    ("9312", "Activități ale cluburilor sportive"),
    ("9313", "Activități ale centrelor de fitness"),
    ("9319", "Alte activități sportive"),
    ("9321", "Bâlciuri și parcuri de distracții"),
    ("9329", "Alte activități recreative și distractive n.c.a."),
    ("9411", "Activități ale organizațiilor economice și patronale"),
    ("9412", "Activități ale organizațiilor profesionale"),
    ("9420", "Activități ale sindicatelor salariaților"),
    ("9491", "Activități ale organizațiilor religioase"),
    ("9492", "Activități ale organizațiilor politice"),
    ("9499", "Activități ale altor organizații n.c.a."),
    ("9511", "Repararea calculatoarelor și a echipamentelor periferice"),
    ("9512", "Repararea echipamentelor de comunicații"),
    ("9521", "Repararea aparatelor electronice de uz casnic"),
    ("9522", "Repararea dispozitivelor de uz gospodăresc și a echipamentelor pentru casă și grădină"),
    ("9523", "Repararea încălțămintei și a articolelor din piele"),
    ("9524", "Repararea mobilei și a furniturilor casnice"),
    ("9525", "Repararea ceasurilor și a bijuteriilor"),
    ("9529", "Repararea articolelor de uz personal și gospodăresc n.c.a."),
    ("9601", "Spălarea și curățarea (uscată) articolelor textile și a produselor din blană"),
    ("9602", "Coafură și alte activități de înfrumusețare"),
    ("9603", "Activități de pompe funebre și similare"),
    ("9604", "Activități de întreținere corporală"),
    ("9609", "Alte activități de servicii n.c.a."),
    ("9700", "Activități ale gospodăriilor private în calitate de angajator de personal casnic"),
    ("9810", "Activități ale gospodăriilor private de producere de bunuri destinate consumului propriu"),
    ("9820", "Activități ale gospodăriilor private de producere de servicii pentru scopuri proprii"),
    ("9900", "Activități ale organizațiilor și organismelor extrateritoriale"),
]

# CAEN code categories (sections)
CAEN_SECTIONS = {
    "A": {"name": "Agricultură, silvicultură și pescuit", "range": ("01", "03")},
    "B": {"name": "Industria extractivă", "range": ("05", "09")},
    "C": {"name": "Industria prelucrătoare", "range": ("10", "33")},
    "D": {"name": "Producția și furnizarea de energie electrică și termică, gaze, apă caldă și aer condiționat", "range": ("35", "35")},
    "E": {"name": "Distribuția apei; salubritate, gestionarea deșeurilor, activități de decontaminare", "range": ("36", "39")},
    "F": {"name": "Construcții", "range": ("41", "43")},
    "G": {"name": "Comerț cu ridicata și cu amănuntul; repararea autovehiculelor și motocicletelor", "range": ("45", "47")},
    "H": {"name": "Transport și depozitare", "range": ("49", "53")},
    "I": {"name": "Hoteluri și restaurante", "range": ("55", "56")},
    "J": {"name": "Informații și comunicații", "range": ("58", "63")},
    "K": {"name": "Intermedieri financiare și asigurări", "range": ("64", "66")},
    "L": {"name": "Tranzacții imobiliare", "range": ("68", "68")},
    "M": {"name": "Activități profesionale, științifice și tehnice", "range": ("69", "75")},
    "N": {"name": "Activități de servicii administrative și activități de servicii suport", "range": ("77", "82")},
    "O": {"name": "Administrație publică și apărare; asigurări sociale din sistemul public", "range": ("84", "84")},
    "P": {"name": "Învățământ", "range": ("85", "85")},
    "Q": {"name": "Sănătate și asistență socială", "range": ("86", "88")},
    "R": {"name": "Activități de spectacole, culturale și recreative", "range": ("90", "93")},
    "S": {"name": "Alte activități de servicii", "range": ("94", "96")},
    "T": {"name": "Activități ale gospodăriilor private în calitate de angajator de personal casnic", "range": ("97", "98")},
    "U": {"name": "Activități ale organizațiilor și organismelor extrateritoriale", "range": ("99", "99")},
}


def get_section_for_code(code: str) -> dict:
    """Determine the section for a CAEN code"""
    prefix = code[:2]
    for section_code, section_info in CAEN_SECTIONS.items():
        start, end = section_info["range"]
        if start <= prefix <= end:
            return {
                "section_code": section_code,
                "section_name": section_info["name"]
            }
    return {"section_code": "?", "section_name": "Necunoscut"}


async def import_caen_codes():
    """Import CAEN codes into MongoDB"""
    
    # Connect to MongoDB
    mongo_url = os.environ.get('MONGO_URL')
    db_name = os.environ.get('DB_NAME', 'mfirme_app')
    
    if not mongo_url:
        print("ERROR: MONGO_URL not set in environment")
        return
    
    client = AsyncIOMotorClient(mongo_url)
    db = client[db_name]
    
    print(f"Connected to MongoDB: {db_name}")
    
    # Prepare records
    records = []
    for code, description in CAEN_REV2_CODES:
        section = get_section_for_code(code)
        
        # Create normalized version for search
        description_normalized = description.upper()
        
        record = {
            "cod": code,
            "denumire": description,
            "denumire_normalized": description_normalized,
            "sectiune": section["section_code"],
            "sectiune_denumire": section["section_name"],
            "versiune": "Rev.2",
            "nivel": "Clasa"  # All entries are at "Clasa" level
        }
        records.append(record)
    
    print(f"Prepared {len(records)} CAEN code records")
    
    # Drop existing collection and create new one
    await db.caen_codes.drop()
    print("Dropped existing caen_codes collection")
    
    # Insert records
    if records:
        await db.caen_codes.insert_many(records)
        print(f"Inserted {len(records)} CAEN codes")
    
    # Create indexes
    await db.caen_codes.create_index("cod", unique=True)
    await db.caen_codes.create_index("denumire_normalized")
    await db.caen_codes.create_index("sectiune")
    await db.caen_codes.create_index([("cod", 1), ("sectiune", 1)])
    
    print("Created indexes")
    
    # Print summary by section
    print("\n=== CAEN Codes by Section ===")
    for section_code in sorted(CAEN_SECTIONS.keys()):
        count = await db.caen_codes.count_documents({"sectiune": section_code})
        if count > 0:
            print(f"  {section_code}: {CAEN_SECTIONS[section_code]['name'][:50]}... ({count} coduri)")
    
    # Total
    total = await db.caen_codes.count_documents({})
    print(f"\nTotal: {total} coduri CAEN Rev.2")
    
    # Sample
    sample = await db.caen_codes.find_one({"cod": "6201"})
    if sample:
        print(f"\nSample (6201 - IT):")
        print(f"  Cod: {sample.get('cod')}")
        print(f"  Denumire: {sample.get('denumire')}")
        print(f"  Secțiune: {sample.get('sectiune')} - {sample.get('sectiune_denumire')}")
    
    client.close()
    print("\nDone!")


if __name__ == "__main__":
    asyncio.run(import_caen_codes())
